import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.support.AbstractApplicationContext;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sungb_000' at '15. 8. 6 오후 11:02' with Gradle 2.5
 *
 * @author sungb_000, @date 15. 8. 6 오후 11:02
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @SuppressWarnings("resource")
	@Test
    public void simpleAtAutowired(){
    	AbstractApplicationContext ac = new AnnotationConfigApplicationContext(Bean1.class, Bean2.class);
    	
    	Bean1 b1 = ac.getBean(Bean1.class);
    	assertNotNull(b1.bean2);
    	
    	assertEquals("abc", b1.msg);
    	assertEquals("Windows 10", b1.osNm);     
    	assertNotNull(b1.osNm);
    }
    

private static class Bean1{
	@Autowired Bean2 bean2;
	@Value("abc") String msg;
	@Value("#{systemProperties['os.name']}") String osNm;
	private static final String msg2 = "fuck";
}

private static class Bean2{
	
}
}
